<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Tk2dUnnFinder</AssemblyName>
    <RootNamespace>Tk2dUnnFinder</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AssetStudio">
      <HintPath>D:\Documents\Knight In Cradle\KnightInCradle\模组源码\tools\AssetLister\bin\Release\net10.0\AssetStudio.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="AssetStudioUtility">
      <HintPath>D:\Documents\Knight In Cradle\KnightInCradle\模组源码\tools\AssetLister\bin\Release\net10.0\AssetStudioUtility.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
